### ISSUE TITLE
Detecting everything as 'Gun'

### ISSUE THREAD

**Issue by Devanshgupta3993** [AlaaSenjab/Real-Time-Weapon-Detection#3]
Hi,
I have been working on your project following [this](https://towardsdatascience.com/detailed-tutorial-build-your-custom-real-time-object-detector-5ade1017fd2d#862a) link.
The training and everything works fine but when the webcam starts, the expected behavious is detect all other objects as N/A but it detects everything as gun. Why is it so?

**Comment by mamidpou** [comment]
@Devanshgupta3993 
Hi i have à question for you please. Did thé training use gpu ? Was it fast ? Because i encoutred This problèm thé gpu's speed Was as fast as cpu's speed
Thanks for respondig too m'y question

**Comment by Devanshgupta3993** [comment]
Hi @mamidpou
yes i used the GPU while training as  i ran  it on the google colab as you mentioned in the tutorial  i  followed every steps mentioned but i encountered a problem while executing  **web interface**  code on the local machine as it gave an error " **convolution theorem failed to execute " cudnn failed**  
 I tried different versions of cuda and cudnn but same  error .I resolved this by uninstalling the cuda and cdnn from laptop. 
After that it worked fine but it as i already mentioned it detect every human as a gun.
So what can i do ?
My laptop GPU -GTX 1650
i7 , 16gb ram.
Thanks

**Comment by mamidpou** [comment]
Well, since i couldn't  train m'y model due too gpu speed that is too low i can't answer your question but i can make some supposition: are the images well labeled ??

**Comment by Devanshgupta3993** [comment]
Thanks for responding  but yes all images are labelled and  tried it on my dataset too which i have created  and labelled it  but same error persist .

**Comment by mamidpou** [comment]
@Devanshgupta3993 
please, i passed the last couple days trying to figure out why the training is too slow. i will be very greatfull if you help me just by executing a litle notebook test to find out why my training is too slow and to figure out the problem.  
https://colab.research.google.com/drive/1EaWha1zW42e8pJ5m2KXKFPe9bzPHhhLf?usp=sharing

**Comment by heytony01** [comment]
@mamidpou 
Hi, I see that you have worked on this project, was wondering if you had a solution for a problem I have. When training the model I get this error:
Traceback (most recent call last):
  File "object_detection/model_main.py", line 108, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "object_detection/model_main.py", line 70, in main
    FLAGS.sample_1_of_n_eval_on_train_examples))
TypeError: create_estimator_and_inputs() missing 1 required positional argument: 'hparams'
