### ISSUE TITLE
TypeError: create_estimator_and_inputs() missing 1 required positional argument: 'hparams'

### ISSUE THREAD

**Issue by heytony01** [AlaaSenjab/Real-Time-Weapon-Detection#4]
When training the model I get this issue:
Traceback (most recent call last):
  File "object_detection/model_main.py", line 108, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "object_detection/model_main.py", line 70, in main
    FLAGS.sample_1_of_n_eval_on_train_examples))
TypeError: create_estimator_and_inputs() missing 1 required positional argument: 'hparams'

**Comment by deoudit** [comment]
I have the same problem when training object detection mobnetssd v1 model.

**Comment by deoudit** [comment]
Can anyone help.

**Comment by deoudit** [comment]
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

Traceback (most recent call last):
  File "model_main.py", line 108, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "model_main.py", line 70, in main
    FLAGS.sample_1_of_n_eval_on_train_examples))
TypeError: create_estimator_and_inputs() missing 1 required positional argument: 'hparams'

**Comment by 227BaronChen** [comment]
Maybe you can try add
```
from object_detection import model_hparams
```
to the `model_main.py` file

**Comment by Suryansh1089** [comment]
> Maybe you can try add
> 
> ```
> from object_detection import model_hparams
> ```
> 
> to the `model_main.py` file

Doesnt work
